repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
    - id: ruff-lint
      name: ruff lint
      entry: ruff check
      language: system
      pass_filenames: false
    - id: ruff-format
      name: ruff format
      entry: ruff format
      language: system
      pass_filenames: false
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      pass_filenames: false
      files: ^retry_later/
